gravitee-io/gravitee-definition

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/ser/RuleSerializer.java
Add api events page with events list, events diff and api rollback features
> API history

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/deser/FailoverDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/deser/ProxyDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/ser/FailoverSerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/ser/ProxySerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/JacksonDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-default-failover.json
- jackson/src/test/resources/io/gravitee/definition/jackson/api-failover-singlecase.json
- jackson/src/test/resources/io/gravitee/definition/jackson/api-override-failover.json
- model/src/main/java/io/gravitee/definition/model/Failover.java
> fix(definition): Remove underscores for failover definition

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/deser/HttpClientOptionsDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/ser/HttpClientOptionsSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/JacksonDeserializerTest.java
- model/src/main/java/io/gravitee/definition/model/HttpClientOptions.java
> feature(definition): Add HTTP pipeling in client options

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/deser/EndpointDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/ser/EndpointSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/JacksonDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-failover-singlecase.json
- model/src/main/java/io/gravitee/definition/model/Endpoint.java
> feat(definition): An endpoint can be a backup endpoint

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/healthcheck/deser/ExpectationDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/healthcheck/deser/HealthCheckDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/healthcheck/ser/ExpectationSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/healthcheck/HealthCheckDeserializerTest.java
- model/src/main/java/io/gravitee/definition/model/services/healthcheck/Expectation.java
> feat(healthcheck): Add a default expectation to check HTTP status code (200)

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/HttpClientDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/HttpProxyDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/HttpClientSerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/HttpProxySerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-overridedhttpconfig.json
- model/src/main/java/io/gravitee/definition/model/HttpProxy.java
- model/src/main/java/io/gravitee/definition/model/HttpProxyType.java
> feat(http): Add proxy configuration between gateway and backend

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/RuleDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/RuleSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-defaultpath.json
- model/src/main/java/io/gravitee/definition/model/Policy.java
- model/src/main/java/io/gravitee/definition/model/Rule.java
> feat(policy): Enable / disable a policy rule

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ApiDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ApiSerializer.java
- model/src/main/java/io/gravitee/definition/model/Api.java
This closes https://github.com/gravitee-io/issues/issues/112
> Allows to group list of APIs by views

- model/src/main/java/io/gravitee/definition/model/Api.java
> fix(healtcheck): Better implementation of the equals method

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ApiDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ApiSerializer.java
- model/src/main/java/io/gravitee/definition/model/Api.java
> fix(definition): Do not store views into definition

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/EndpointDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ProxyDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/EndpointSerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ProxySerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-multitenant.json
- model/src/main/java/io/gravitee/definition/model/Endpoint.java
- model/src/main/java/io/gravitee/definition/model/Proxy.java
> feat(gateway): Multi-tenant support

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ProxyDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ProxySerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-default-failover.json
- jackson/src/test/resources/io/gravitee/definition/jackson/api-multiplesameendpoints.json
- model/src/main/java/io/gravitee/definition/model/Endpoint.java
- model/src/main/java/io/gravitee/definition/model/Proxy.java
> fix(endpoints): endpoints with same name are allowed

- model/src/test/java/io/gravitee/definition/model/PropertiesTest.java
> chore(properties): add UT

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/core/deser/ScheduledServiceDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/core/deser/ServiceDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/healthcheck/deser/HealthCheckDeserializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/dynamicproperty/DynamicPropertyServiceDeserializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/healthcheck/HealthCheckServiceDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/services/api-withservices-v2.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/api-withservices.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/dynamicproperty/api-withservice-dynamicproperty-unitInLowerCase.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-noExpectation.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-unitInLowerCase.json
> fix(health-check): Do not parse data if service is disabled

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ProxyDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ProxySerializer.java
- model/src/main/java/io/gravitee/definition/model/LoggingMode.java
- model/src/main/java/io/gravitee/definition/model/Proxy.java
> feat(logging): Add API logging in place of HTTP dump

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/HttpClientOptionsDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/HttpClientOptionsSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-withclientoptions.json
- model/src/main/java/io/gravitee/definition/model/HttpClientOptions.java
> feat(gateway): Add follow HTTP redirect option at endpoint level

- model/src/main/java/io/gravitee/definition/model/Failover.java
> fix(failover): set the default timeout > 0

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/EndpointDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ProxyDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ProxySerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/endpoint/HttpEndpointSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiSerializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-multitenants.json
- model/src/main/java/io/gravitee/definition/model/Endpoint.java
- model/src/main/java/io/gravitee/definition/model/Proxy.java
Closes gravitee-io/issues#1056
> feat(tenant): An endpoint can be associated to multiple tenants

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ApiModule.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/EndpointGroupDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ProxyDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/EndpointGroupSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/services/api-withservices-v2.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/api-withservices.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/dynamicproperty/api-withservice-dynamicproperty-v2.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/dynamicproperty/api-withservice-dynamicproperty.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-badUnit.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-noExpectation.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-unitInLowerCase.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-v2-fromroot.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-v2.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck.json
- model/src/main/java/io/gravitee/definition/model/EndpointGroup.java
- model/src/main/java/io/gravitee/definition/model/Proxy.java
> feat(gateway): Manage group of endpoints

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ApiDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ApiSerializer.java
- model/src/main/java/io/gravitee/definition/model/Api.java
This closes gravitee-io/issues#1312
> feat: display top paths/resources in analytics

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ApiModule.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/LoggingDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ProxyDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/LoggingSerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ProxySerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiSerializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-logging-client.json
- jackson/src/test/resources/io/gravitee/definition/jackson/api-logging.json
- model/src/main/java/io/gravitee/definition/model/Logging.java
- model/src/main/java/io/gravitee/definition/model/Proxy.java
Closes gravitee-io/issues#1482
> feat(logging): Define a condition to log a request

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ApiDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ApiSerializer.java
> fix(history): errors on rollback

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/HttpClientSslOptionsDeserializer.java
Closes gravitee-io/issues#1647
>  fix(api): Do not manage unknown trustore or keystore for SSL configuration

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/RuleDeserializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- model/src/main/java/io/gravitee/definition/model/Rule.java
Closes gravitee-io/issues#1622
> feat(gateway): Performance improvements

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/endpoint/HttpEndpointDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/endpoint/HttpEndpointSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiSerializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-headers.json
- model/src/main/java/io/gravitee/definition/model/endpoint/HttpEndpoint.java
Closes gravitee-io/issues#1740
> feat(gateway): Add default HTTP headers to endpoints

- jackson/pom.xml
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ApiModule.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ProxyDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/VirtualHostDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ProxySerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/VirtualHostSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiSerializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/ServicesSerializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/discovery/EndpointDiscoveryServiceSerializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/dynamicproperty/DynamicPropertyServiceSerializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/healthcheck/HealthCheckServiceSerializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-defaulthttpconfig.json
- jackson/src/test/resources/io/gravitee/definition/jackson/api-virtualhosts.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/api-withservices-v2-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/discovery/api-withoutservice-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/discovery/api-withservice-consul-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/dynamicproperty/api-withservice-dynamicproperty-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-v2-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-v2-fromroot-expected.json
- model/pom.xml
- model/src/main/java/io/gravitee/definition/model/Proxy.java
- model/src/main/java/io/gravitee/definition/model/VirtualHost.java
- pom.xml
Closes gravitee-io/issues#1594
> feat(gateway): Add Virtual-Host support

- .gitignore
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/HttpClientOptionsDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/HttpClientOptionsSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-withclientoptions.json
- model/src/main/java/io/gravitee/definition/model/HttpClientOptions.java
Closes gravitee-io/issues#2634
> feat(gateway): remove encodeURI

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/CorsDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/CorsSerializer.java
- model/src/main/java/io/gravitee/definition/model/Cors.java
> fix(cors): add regex support

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/CorsDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/CorsSerializer.java
- model/src/main/java/io/gravitee/definition/model/Cors.java
> chore: Merge 1.30.11

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ApiModule.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/EndpointDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/EndpointGroupDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/HttpClientOptionsDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/endpoint/GrpcEndpointDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/endpoint/HttpEndpointDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/HttpClientOptionsSerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/endpoint/GrpcEndpointSerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/endpoint/HttpEndpointSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiSerializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-grpc-endpoint-ssl.json
- jackson/src/test/resources/io/gravitee/definition/jackson/api-grpc-endpoint-without-type.json
- jackson/src/test/resources/io/gravitee/definition/jackson/api-grpc-endpoint.json
- jackson/src/test/resources/io/gravitee/definition/jackson/api-http2-endpoint.json
- model/src/main/java/io/gravitee/definition/model/HttpClientOptions.java
- model/src/main/java/io/gravitee/definition/model/ProtocolVersion.java
- model/src/main/java/io/gravitee/definition/model/endpoint/GrpcEndpoint.java
- model/src/main/java/io/gravitee/definition/model/endpoint/HttpEndpoint.java
Closes gravitee-io/issues#3105
> feat(grpc): Add GRPC support

- model/src/main/java/io/gravitee/definition/model/Endpoint.java
- model/src/main/java/io/gravitee/definition/model/endpoint/EndpointStatusListener.java
Closes gravitee-io/issues#3877
> feat(endpoint): Manage secondary endpoints

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ApiSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiSerializerTest.java
> fix: Add consistency on field properties in EL

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/HttpProxyDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/HttpProxySerializer.java
- model/src/main/java/io/gravitee/definition/model/HttpProxy.java
Closes gravitee-io/issues#4256
> feat(proxy): allow use of system proxy in endpoint configuration

- model/src/main/java/io/gravitee/definition/model/VirtualHost.java
Closes gravitee-io/issues#4295
> feat(management): add equals and hashCode method

- model/src/main/java/io/gravitee/definition/model/Api.java
- model/src/main/java/io/gravitee/definition/model/Cors.java
- model/src/main/java/io/gravitee/definition/model/Endpoint.java
- model/src/main/java/io/gravitee/definition/model/EndpointGroup.java
- model/src/main/java/io/gravitee/definition/model/Failover.java
- model/src/main/java/io/gravitee/definition/model/HttpClient.java
- model/src/main/java/io/gravitee/definition/model/HttpClientOptions.java
- model/src/main/java/io/gravitee/definition/model/HttpClientSslOptions.java
- model/src/main/java/io/gravitee/definition/model/HttpProxy.java
- model/src/main/java/io/gravitee/definition/model/LoadBalancer.java
- model/src/main/java/io/gravitee/definition/model/Logging.java
- model/src/main/java/io/gravitee/definition/model/Path.java
- model/src/main/java/io/gravitee/definition/model/Policy.java
- model/src/main/java/io/gravitee/definition/model/Properties.java
- model/src/main/java/io/gravitee/definition/model/Property.java
- model/src/main/java/io/gravitee/definition/model/Proxy.java
- model/src/main/java/io/gravitee/definition/model/ResponseTemplate.java
- model/src/main/java/io/gravitee/definition/model/ResponseTemplates.java
- model/src/main/java/io/gravitee/definition/model/Rule.java
- model/src/main/java/io/gravitee/definition/model/Service.java
- model/src/main/java/io/gravitee/definition/model/VirtualHost.java
- model/src/main/java/io/gravitee/definition/model/plugins/resources/Resource.java
- model/src/main/java/io/gravitee/definition/model/services/Services.java
- model/src/main/java/io/gravitee/definition/model/services/dynamicproperty/DynamicPropertyProviderConfiguration.java
- model/src/main/java/io/gravitee/definition/model/services/healthcheck/Request.java
- model/src/main/java/io/gravitee/definition/model/services/healthcheck/Response.java
- model/src/main/java/io/gravitee/definition/model/services/healthcheck/Step.java
- model/src/main/java/io/gravitee/definition/model/services/schedule/Trigger.java
- model/src/main/java/io/gravitee/definition/model/ssl/KeyStore.java
- model/src/main/java/io/gravitee/definition/model/ssl/TrustStore.java
Closes gravitee-io/issues#4493
> feat(cluster): Add clustering capabilities

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/core/deser/ScheduledServiceDeserializer.java
> fix(scheduled-service): we should not lost the polling configuration if we disable a service

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ApiDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ApiSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiSerializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-bestMatchFlowMode.json
- model/src/main/java/io/gravitee/definition/model/Api.java
- model/src/main/java/io/gravitee/definition/model/FlowMode.java
Fixes https://github.com/gravitee-io/issues/issues/4589
> feat: allow to migrate from policy studio v1 to v2

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/LoggingDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/LoggingSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/api-logging-client.json
- model/src/main/java/io/gravitee/definition/model/Logging.java
- model/src/main/java/io/gravitee/definition/model/LoggingContent.java
- model/src/main/java/io/gravitee/definition/model/LoggingScope.java
> feat(management): improve API logging configuration

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/core/deser/ScheduledServiceDeserializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/healthcheck/HealthCheckServiceDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-disabled.json
Closes gravitee-io/issues#5042
> fix: Handle the deser of a configuration of HC disabled

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/dynamicproperty/deser/http/HttpDynamicPropertyProviderConfigurationDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/dynamicproperty/ser/http/HttpDynamicPropertyProviderConfigurationSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/dynamicproperty/DynamicPropertyServiceDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/services/api-withservices-v2.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/api-withservices-v3-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/api-withservices-v3.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/api-withservices.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/dynamicproperty/api-withservice-dynamicproperty-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/dynamicproperty/api-withservice-dynamicproperty-unitInLowerCase.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/dynamicproperty/api-withservice-dynamicproperty-v2.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/dynamicproperty/api-withservice-dynamicproperty-v3.json
- jackson/src/test/resources/io/gravitee/definition/jackson/services/dynamicproperty/api-withservice-dynamicproperty.json
- model/src/main/java/io/gravitee/definition/model/services/dynamicproperty/http/HttpDynamicPropertyProviderConfiguration.java
- model/src/main/java/io/gravitee/definition/model/services/schedule/Trigger.java
Fixes https://github.com/gravitee-io/issues/issues/4746
> feat: define HTTP verb for dynamic properties and dictionaries

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/core/deser/ScheduledServiceDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/core/ser/ScheduledServiceSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/healthcheck/HealthCheckServiceDeserializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/healthcheck/HealthCheckServiceSerializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withservice-healthcheck-expected.json
> fix(health-check): handle null 'schedule' field on disabled health check

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/PropertiesAsListDeserializer.java
Related to gravitee-io/issues#5642
> feat(jackson): add PropertiesAsListDeserializer

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/VirtualHostDeserializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/VirtualHostDeserializerTest.java
> fix: manage '/' contextpath for Virtualhost

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/GraviteeMapper.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/DebugApiModule.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/ApiDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/DebugApiDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/HttpRequestDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/HttpResponseDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/ApiSerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/DebugApiSerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/HttpRequestSerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/HttpResponseSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/HttpRequestDeserializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/HttpRequestSerializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/HttpResponseDeserializerTest.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/HttpResponseSerializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/httprequest-multivalueheaders-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/httprequest-multivalueheaders.json
- jackson/src/test/resources/io/gravitee/definition/jackson/httprequest-simpleheaders-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/httprequest-simpleheaders.json
- jackson/src/test/resources/io/gravitee/definition/jackson/httpresponse-multivalueheaders-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/httpresponse-multivalueheaders.json
- jackson/src/test/resources/io/gravitee/definition/jackson/httpresponse-simpleheaders-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/httpresponse-simpleheaders.json
- model/src/main/java/io/gravitee/definition/model/DebugApi.java
- model/src/main/java/io/gravitee/definition/model/DebugStatus.java
- model/src/main/java/io/gravitee/definition/model/HttpRequest.java
- model/src/main/java/io/gravitee/definition/model/HttpResponse.java
> feat: handle debug mode

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/EndpointDeserializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/healthcheck/HealthCheckServiceDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/services/healtcheck/api-withoutservice-healthcheck.json
> fix: ignore the "healthcheck" field when importing

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/services/core/deser/ScheduledServiceDeserializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/services/core/ScheduledServiceDeserializerTest.java
> fix(healthcheck): convert old rate config to cron

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/StepDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/StepSerializer.java
- model/src/main/java/io/gravitee/definition/model/flow/Step.java
https://github.com/gravitee-io/issues/issues/6629
> feat: add execution condition to steps

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/DebugStepDeserializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/DebugApiDeserializerTest.java
- model/src/main/java/io/gravitee/definition/model/debug/DebugStep.java
- model/src/main/java/io/gravitee/definition/model/debug/DebugStepStatus.java
**Issue**
https://github.com/gravitee-io/issues/issues/6950
**Description**
Add an enum for DebugStepStatus
> feat: add a DebugStepStatus

- model/src/main/java/io/gravitee/definition/model/debug/DebugStepStatus.java
**Issue**
https://github.com/gravitee-io/issues/issues/6951
> feat: add SKIPPED status to DebugStepStatus

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/GraviteeMapper.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ApiModule.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/EndpointDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/EndpointGroupSerializer.java
- model/src/main/java/io/gravitee/definition/model/Endpoint.java
**Issue**
https://github.com/gravitee-io/issues/issues/7268
> Merge 1.32.1

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/DebugApiModule.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/DebugApiDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/DebugMetricsDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/DebugApiSerializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/DebugMetricsSerializer.java
- jackson/src/test/resources/io/gravitee/definition/jackson/debug/debug-api-with-backend-response-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/debug/debug-api-with-backend-response.json
- model/src/main/java/io/gravitee/definition/model/debug/DebugApi.java
- model/src/main/java/io/gravitee/definition/model/debug/DebugMetrics.java
> feat(debug): add metrics to debug api

- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/deser/DebugStepDeserializer.java
- jackson/src/main/java/io/gravitee/definition/jackson/datatype/api/ser/DebugStepSerializer.java
- jackson/src/test/java/io/gravitee/definition/jackson/api/DebugApiDeserializerTest.java
- jackson/src/test/resources/io/gravitee/definition/jackson/debug/debug-api-with-debug-steps-expected.json
- jackson/src/test/resources/io/gravitee/definition/jackson/debug/debug-api-with-debug-steps.json
- model/src/main/java/io/gravitee/definition/model/debug/DebugStep.java
**Issue**
https://github.com/gravitee-io/issues/issues/7226
**Description**
Add condition to DebugStep
**Additional context**
> feat: add condition to DebugStep
